/**
 * Centralized Error Codes for consistent error handling across the system
 * Each error code should be unique and descriptive
 */

export const ErrorCodes = {
  // Authentication Errors (AUTH_*)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_LOCKED_OUT: 'AUTH_ACCOUNT_LOCKED_OUT',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
  AUTH_CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',

  // Authorization Errors (AUTHZ_*)
  AUTHZ_INVALID_TOKEN: 'AUTHZ_INVALID_TOKEN',
  AUTHZ_INVALID_REFRESH_TOKEN: 'AUTHZ_INVALID_REFRESH_TOKEN',
  AUTHZ_NO_AUTH_HEADER: 'AUTHZ_NO_AUTH_HEADER',
  AUTHZ_INVALID_AUTH_FORMAT: 'AUTHZ_INVALID_AUTH_FORMAT',
  AUTHZ_INVALID_SESSION: 'AUTHZ_INVALID_SESSION',

  // Two-Factor Authentication Errors (2FA_*)
  TWO_FA_INVALID_TOKEN: 'TWO_FA_INVALID_TOKEN',
  TWO_FA_ALREADY_ENABLED: 'TWO_FA_ALREADY_ENABLED',
  TWO_FA_NOT_ENABLED: 'TWO_FA_NOT_ENABLED',
  TWO_FA_SETUP_NOT_INITIATED: 'TWO_FA_SETUP_NOT_INITIATED',

  // Token/Reset Errors (TOKEN_*)
  TOKEN_INVALID_OR_EXPIRED_RESET: 'TOKEN_INVALID_OR_EXPIRED_RESET',
  TOKEN_INVALID_VERIFICATION: 'TOKEN_INVALID_VERIFICATION',

  // Session Management Errors (SESSION_*)
  SESSION_FAILED_TO_LIST: 'SESSION_FAILED_TO_LIST',
  SESSION_FAILED_TO_REVOKE: 'SESSION_FAILED_TO_REVOKE',
  SESSION_FAILED_TO_REVOKE_ALL: 'SESSION_FAILED_TO_REVOKE_ALL',
  SESSION_FAILED_TO_SIGN_OUT: 'SESSION_FAILED_TO_SIGN_OUT',
  SESSION_FAILED_TO_CHANGE_PASSWORD: 'SESSION_FAILED_TO_CHANGE_PASSWORD',

  // Registration Errors (REG_*)
  REG_FAILED_TO_SIGN_UP: 'REG_FAILED_TO_SIGN_UP',

  // User Errors (USER_*)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NOT_AUTHENTICATED: 'USER_NOT_AUTHENTICATED',

  // Role/Permission Errors (ROLE_*)
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_CANNOT_DELETE_SYSTEM_ROLE: 'ROLE_CANNOT_DELETE_SYSTEM_ROLE',

  // Plugin Management Errors (PLUGIN_*)
  PLUGIN_ID_OR_NAME_REQUIRED: 'PLUGIN_ID_OR_NAME_REQUIRED',
  PLUGIN_SERVICE_NOT_FOUND: 'PLUGIN_SERVICE_NOT_FOUND',

  // Validation Errors (VAL_*)
  VAL_INPUT_REQUIRED: 'VAL_INPUT_REQUIRED',
  VAL_STATUS_REQUIRED: 'VAL_STATUS_REQUIRED',

  // Saga/Workflow Errors (SAGA_*)
  SAGA_HASHED_PASSWORD_NOT_FOUND: 'SAGA_HASHED_PASSWORD_NOT_FOUND',
  SAGA_USER_ID_NOT_FOUND: 'SAGA_USER_ID_NOT_FOUND',
  SAGA_USER_DATA_NOT_FOUND: 'SAGA_USER_DATA_NOT_FOUND',
  SAGA_ROLE_NOT_FOUND: 'SAGA_ROLE_NOT_FOUND',
  SAGA_USER_ALREADY_EXISTS: 'SAGA_USER_ALREADY_EXISTS',
  SAGA_UNABLE_TO_GENERATE_USERNAME: 'SAGA_UNABLE_TO_GENERATE_USERNAME',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

/**
 * Helper type for error responses with error codes
 */
export interface ErrorWithCode {
  message: string;
  code: ErrorCode;
  requestId?: string;
}
