#!/usr/bin/env bun
/**
 * Stitch multiple GraphQL schemas into a federated schema
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';

async function stitchSchemas() {
  console.log('🔗 Stitching GraphQL schemas...\n');
  
  const schemasDir = resolve('src/generated');
  const schemaFiles = [
    'user-service.graphql',
    'payment-service.graphql',
  ];
  
  let federatedSchema = `
# Federated GraphQL Schema
# Generated by: npm run schema:stitch
# Date: ${new Date().toISOString()}

`;
  
  let schemasProcessed = 0;
  
  for (const schemaFile of schemaFiles) {
    const schemaPath = resolve(schemasDir, schemaFile);
    
    if (existsSync(schemaPath)) {
      console.log(`📄 Processing ${schemaFile}...`);
      
      const schemaContent = readFileSync(schemaPath, 'utf-8');
      const serviceName = schemaFile.replace('.graphql', '');
      
      federatedSchema += `
# ===== ${serviceName.toUpperCase()} SERVICE =====
${schemaContent}

`;
      schemasProcessed++;
    } else {
      console.warn(`⚠️  Schema file not found: ${schemaPath}`);
    }
  }
  
  if (schemasProcessed === 0) {
    throw new Error('No schema files found to stitch');
  }
  
  // Write federated schema
  const outputPath = resolve(schemasDir, 'federated-schema.graphql');
  writeFileSync(outputPath, federatedSchema);
  
  console.log(`✅ Federated schema created: ${outputPath}`);
  console.log(`📊 Schemas stitched: ${schemasProcessed}/${schemaFiles.length}`);
  
  return outputPath;
}

async function main() {
  try {
    const outputPath = await stitchSchemas();
    
    console.log('\n🎉 Schema stitching completed successfully!');
    console.log('\n🚀 Next steps:');
    console.log('   npm run start:dev      # Start API Gateway');
    console.log('   npm run codegen        # Generate TypeScript types');
    
  } catch (error) {
    console.error('❌ Schema stitching failed:', error.message);
    console.log('\n💡 Make sure to run: npm run schema:download first');
    process.exit(1);
  }
}

main();
